global:
  # HTTP client configuration

# The directory from which notification templates are read
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 20s
  group_interval: 5m
  repeat_interval: 3h
  receiver: discord_webhook

receivers:
- name: 'discord_webhook'
  webhook_configs:
  - url: 'http://webhook:9094'
    text: 'Watchdog Alert!'
