# TODO: Isolate frontend and backend networks for better security

version: "2.0"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    # networks:
    #   - frontend
    #   - backend
    container_name: nginx
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    # networks:
    #   - frontend
    #   - backend
    container_name: prometheus
  grafana:
    build: ./grafana
    ports: 
      - "3000:3000"
    # networks:
    #     - frontend
    #     - backend
    volumes:
        - grafana_etc:/etc/grafana
        - grafana_usr:/usr/share/grafana 
        - grafana_var:/var/lib/grafana
    container_name: grafana
  bme280:
    build: ./bme280
    privileged: true
    ports:
      - "5000:5000"
    # networks:
    #   - backend
    container_name: bme280
  node_exporter:
    build: ./node_exporter
    # networks:
    #   - backend
    container_name: node_exporter
  opencv:
    build: ./opencv
    restart: always
    privileged: true
    container_name: opencv
    # networks:
    #   - backend
    ports:
      - "8000:8000"
    labels:
      io.balena.features.kernel-modules: '1'
  alertmanager:
    build: ./alertmanager
    privileged: true
    volumes:
      - alertmanager:/alertmanager/
    ports:
      - '9093:9093'
  alertmanager-discord:
    image: benjojo/alertmanager-discord
    restart: always
    container_name: alertmanager-discord
    ports:
      - "9094:9094"
    environment:
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/843548957270999110/IGYr_zOpZ_qhMIoiYLrGQ8URNCPrf_iXXzi-HpIO68yPsr7rlctYX2WTQEZiSxsS3ska

# networks:
#     frontend:
#     backend:

volumes:
    grafana_etc:
    grafana_usr:
    grafana_var:
    alertmanager: