global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: sensor
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
    - targets: ['sensor:5000']
  - job_name: node_exporter
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
    - targets: ['node_exporter:9100']


